language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t weslleydavid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true weslleydavid/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-sa-east-1-421763509082"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY